# webforJ configuration
webforj.entry = com.webforjkotlinstarter.Application
webforj.debug = true
webforj.version=@webforj.version@
webforj.devtools.livereload.enabled=true
webforj.devtools.livereload.static-resources-enabled=true
webforj.devtools.browser.open=true

# Spring configuration
server.shutdown=immediate
spring.application.name=webforj-kotlin-starter
spring.devtools.livereload.enabled=false

# H2 Database configuration
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# JPA configuration
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.open-in-view=false

# H2 Console (optional - for development)
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
